// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkt.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	pkt.proto

It has these top-level messages:
	PacketDemo
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PacketDemo struct {
	Version    int32  `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	Chidcli    int32  `protobuf:"varint,2,opt,name=Chidcli" json:"Chidcli,omitempty"`
	Chidsrv    int32  `protobuf:"varint,3,opt,name=Chidsrv" json:"Chidsrv,omitempty"`
	Command    string `protobuf:"bytes,4,opt,name=Command" json:"Command,omitempty"`
	Remoteip   string `protobuf:"bytes,5,opt,name=Remoteip" json:"Remoteip,omitempty"`
	Remoteport string `protobuf:"bytes,6,opt,name=Remoteport" json:"Remoteport,omitempty"`
	Conv       uint32 `protobuf:"varint,7,opt,name=Conv" json:"Conv,omitempty"`
	Msgid      uint64 `protobuf:"varint,8,opt,name=Msgid" json:"Msgid,omitempty"`
	Compress   bool   `protobuf:"varint,9,opt,name=Compress" json:"Compress,omitempty"`
	Data       string `protobuf:"bytes,10,opt,name=Data" json:"Data,omitempty"`
}

func (m *PacketDemo) Reset()                    { *m = PacketDemo{} }
func (m *PacketDemo) String() string            { return proto.CompactTextString(m) }
func (*PacketDemo) ProtoMessage()               {}
func (*PacketDemo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PacketDemo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PacketDemo) GetChidcli() int32 {
	if m != nil {
		return m.Chidcli
	}
	return 0
}

func (m *PacketDemo) GetChidsrv() int32 {
	if m != nil {
		return m.Chidsrv
	}
	return 0
}

func (m *PacketDemo) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *PacketDemo) GetRemoteip() string {
	if m != nil {
		return m.Remoteip
	}
	return ""
}

func (m *PacketDemo) GetRemoteport() string {
	if m != nil {
		return m.Remoteport
	}
	return ""
}

func (m *PacketDemo) GetConv() uint32 {
	if m != nil {
		return m.Conv
	}
	return 0
}

func (m *PacketDemo) GetMsgid() uint64 {
	if m != nil {
		return m.Msgid
	}
	return 0
}

func (m *PacketDemo) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

func (m *PacketDemo) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*PacketDemo)(nil), "main.PacketDemo")
}

func init() { proto.RegisterFile("pkt.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4a, 0xc6, 0x30,
	0x14, 0x46, 0xc9, 0x6f, 0xfa, 0xb7, 0xbd, 0xe0, 0x12, 0x1c, 0x2e, 0x0e, 0x12, 0x9c, 0x32, 0xb9,
	0xf8, 0x08, 0xed, 0x2a, 0x48, 0x06, 0xf7, 0xd8, 0x06, 0x0d, 0x35, 0xb9, 0x21, 0x09, 0x7d, 0x08,
	0x9f, 0x5a, 0x9a, 0xda, 0xea, 0x76, 0x4e, 0x0e, 0x7c, 0x81, 0x0b, 0x7d, 0x5c, 0xca, 0x53, 0x4c,
	0x54, 0x48, 0x70, 0x6f, 0x5c, 0x78, 0xfc, 0xbe, 0x00, 0xbc, 0x9a, 0x69, 0xb1, 0x65, 0xb4, 0x9e,
	0x04, 0x42, 0xfb, 0x66, 0x53, 0x76, 0x14, 0x90, 0x49, 0xa6, 0x1a, 0x7d, 0xe8, 0x56, 0x86, 0x4f,
	0x37, 0x4f, 0x5f, 0x0e, 0x2f, 0x7b, 0xf9, 0xd5, 0xa3, 0xe4, 0xb4, 0xe2, 0xcd, 0x5f, 0xc9, 0x69,
	0xad, 0x85, 0xbc, 0x37, 0x61, 0x46, 0x2e, 0x99, 0xea, 0xf5, 0xa1, 0xe2, 0x1e, 0x3a, 0x6d, 0x3d,
	0x15, 0xeb, 0x22, 0x36, 0x35, 0x9d, 0x2e, 0x1e, 0x00, 0x76, 0x8e, 0x94, 0x0a, 0x5e, 0x6b, 0xfd,
	0xf7, 0x22, 0x04, 0xf0, 0x81, 0xc2, 0x8a, 0xad, 0x64, 0xea, 0x56, 0x57, 0x16, 0x77, 0xd0, 0xbc,
	0xe4, 0x0f, 0x37, 0x63, 0x27, 0x99, 0xe2, 0x7a, 0x97, 0xed, 0x97, 0x81, 0x7c, 0x4c, 0x36, 0x67,
	0xec, 0x25, 0x53, 0x9d, 0x3e, 0x7d, 0x5b, 0x19, 0x4d, 0x31, 0x08, 0x75, 0xbf, 0xf2, 0xfb, 0xb5,
	0x5e, 0xe6, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x02, 0x7d, 0xc8, 0x30, 0x26, 0x01, 0x00, 0x00,
}
