// Code generated by go-bindata.
// sources:
// toxnodes.json
// DO NOT EDIT!

package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)
type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _toxnodesJson = []byte(`{
    "last_scan": 1495114700,
    "last_refresh": 1495114461,
    "nodes": [
        {
            "ipv4": "biribiri.org",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                33445,
                3389
            ],
            "public_key": "F404ABAA1C99A9D37D61AB54898F56793E1DEF8BD46B1038B9D822E8460FAB67",
            "maintainer": "nurupo",
            "location": "US",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Welcome, stranger #9193. I'm up for 6d 09h 29m 55s, running since May 12 04:08:25 UTC. If I get outdated, please ping my maintainer at nurupo.contributions@gmail.com",
            "last_ping": 1495114700
        },
        {
            "ipv4": "nodes.tox.chat",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                33445,
                3389
            ],
            "public_key": "6FC41E2BD381D37E9748FC0E0328CE086AF9598BECC8FEB7DDF2E440475F300E",
            "maintainer": "Impyy",
            "location": "NL",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Straps boots like no other",
            "last_ping": 1495114700
        },
        {
            "ipv4": "130.133.110.14",
            "ipv6": "2001:6f8:1c3c:babe::14:1",
            "port": 33445,
            "tcp_ports": [
                33445
            ],
            "public_key": "461FA3776EF0FA655F1A05477DF1B3B614F7D6B124F7DB1DD4FE3C08B03B640F",
            "maintainer": "Manolis",
            "location": "DE",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Spline tox bootstrap node",
            "last_ping": 1495114702
        },
        {
            "ipv4": "205.185.116.116",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "A179B09749AC826FF01F37A9613F6B57118AE014D4196A0E1105A98F93A54702",
            "maintainer": "Busindre",
            "location": "US",
            "status_udp": true,
            "status_tcp": true,
            "version": "2014101200",
            "motd": "tox-bootstrapd",
            "last_ping": 1495114700
        },
        {
            "ipv4": "198.98.51.198",
            "ipv6": "2605:6400:1:fed5:22:45af:ec10:f329",
            "port": 33445,
            "tcp_ports": [
                33445,
                3389
            ],
            "public_key": "1D5A5F2F5D6233058BF0259B09622FB40B482E4FA0931EB8FD3AB8E7BF7DAF6F",
            "maintainer": "Busindre",
            "location": "US",
            "status_udp": true,
            "status_tcp": true,
            "version": "2014101200",
            "motd": "tox-bootstrapd",
            "last_ping": 1495114700
        },
        {
            "ipv4": "108.61.165.198",
            "ipv6": "2001:19f0:5000:8121:5054:ff:fe1c:9ded",
            "port": 33445,
            "tcp_ports": [

            ],
            "public_key": "8E7D0B859922EF569298B4D261A8CCB5FEA14FB91ED412A7603A585A25698832",
            "maintainer": "ray65536",
            "location": "NL",
            "status_udp": true,
            "status_tcp": false,
            "version": "2016010100",
            "motd": "Ray's Tox Node",
            "last_ping": 1495114700
        },
        {
            "ipv4": "194.249.212.109",
            "ipv6": "2001:1470:fbfe::109",
            "port": 33445,
            "tcp_ports": [
                33445,
                3389
            ],
            "public_key": "3CEE1F054081E7A011234883BC4FC39F661A55B73637A5AC293DDF1251D9432B",
            "maintainer": "fluke571",
            "location": "SI",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "tox-bootstrapd",
            "last_ping": 1495114702
        },
        {
            "ipv4": "185.25.116.107",
            "ipv6": "2a00:7a60:0:746b::3",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "DA4E4ED4B697F2E9B000EEFE3A34B554ACD3F45F5C96EAEA2516DD7FF9AF7B43",
            "maintainer": "MAH69K",
            "location": "UA",
            "status_udp": true,
            "status_tcp": true,
            "version": "",
            "motd": "",
            "last_ping": 1495114700
        },
        {
            "ipv4": "5.189.176.217",
            "ipv6": "2a02:c200:1:10:3:1:605:1337",
            "port": 5190,
            "tcp_ports": [
                33445,
                5190,
                3389
            ],
            "public_key": "2B2137E094F743AC8BD44652C55F41DFACC502F125E99E4FE24D40537489E32F",
            "maintainer": "tastytea",
            "location": "DE",
            "status_udp": true,
            "status_tcp": true,
            "version": "",
            "motd": "",
            "last_ping": 1495114700
        },
        {
            "ipv4": "217.182.143.254",
            "ipv6": "2001:41d0:302:1000::e111",
            "port": 2306,
            "tcp_ports": [
                443,
                2306,
                33445
            ],
            "public_key": "7AED21F94D82B05774F697B209628CD5A9AD17E0C073D9329076A4C28ED28147",
            "maintainer": "pucetox",
            "location": "FR",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "by pucetox,\nipv4/ipv6 UDP:2306 TCP:21/80/443/2306/33445\nsync your nodes here tox.0x10k.com/bootstrapd-conf , \n for communication: 1D1C0B992DEB6D7F18561176F7F5E572BCC7F2BA5CFA7E9E437B9134122CE96D906A6119F9D2",
            "last_ping": 1495114702
        },
        {
            "ipv4": "104.223.122.15",
            "ipv6": "2607:ff48:aa81:800::35eb:1",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "0FB96EEBFB1650DDB52E70CF773DDFCABE25A95CC3BB50FC251082E4B63EF82A",
            "maintainer": "ru_maniac",
            "location": "US",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "built on: Tue Feb 21st 2017, 10:52:30 UTC+3\nplease note: running on TokTox Toxcore!\nmore info on the matter: goo.gl/Gz5KhK & goo.gl/i2TZJr\n\ntox id for queries and general info: EBD2A7B649ABB10ED9F47E5113F04000F39D46F087CEB62FCCE1069471FD6915256D197F2A97",
            "last_ping": 1495114700
        },
        {
            "ipv4": "tox.verdict.gg",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                33445,
                3389
            ],
            "public_key": "1C5293AEF2114717547B39DA8EA6F1E331E5E358B35F9B6B5F19317911C5F976",
            "maintainer": "Deliran",
            "location": "DE",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Praise The Sun!",
            "last_ping": 1495114700
        },
        {
            "ipv4": "d4rk4.ru",
            "ipv6": "-",
            "port": 1813,
            "tcp_ports": [
                1813
            ],
            "public_key": "53737F6D47FA6BD2808F378E339AF45BF86F39B64E79D6D491C53A1D522E7039",
            "maintainer": "D4rk4",
            "location": "RU",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "TOX ID: 35EDC07AEB18B163E07EE33F6CDDA63969F394FF6A617CEAB22A7EBBEAAAF854C0EDFBD46898",
            "last_ping": 1495114702
        },
        {
            "ipv4": "104.233.104.126",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "EDEE8F2E839A57820DE3DA4156D88350E53D4161447068A3457EE8F59F362414",
            "maintainer": "wildermesser",
            "location": "CA",
            "status_udp": true,
            "status_tcp": true,
            "version": "2014101200",
            "motd": "tox-bootstrapd",
            "last_ping": 1495114700
        },
        {
            "ipv4": "51.254.84.212",
            "ipv6": "2001:41d0:a:1a3b::18",
            "port": 33445,
            "tcp_ports": [
                33445,
                3389
            ],
            "public_key": "AEC204B9A4501412D5F0BB67D9C81B5DB3EE6ADA64122D32A3E9B093D544327D",
            "maintainer": "a68366",
            "location": "FR",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Since 26.12.2015",
            "last_ping": 1495114700
        },
        {
            "ipv4": "88.99.133.52",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "2D320F971EF2CA18004416C2AAE7BA52BF7949DB34EA8E2E21AF67BD367BE211",
            "maintainer": "Skey",
            "location": "FR",
            "status_udp": true,
            "status_tcp": true,
            "version": "2014101200",
            "motd": "tox-bootstrapd",
            "last_ping": 1495114700
        },
        {
            "ipv4": "185.58.206.164",
            "ipv6": "2a02:f680:1:1100::3313",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "24156472041E5F220D1FA11D9DF32F7AD697D59845701CDD7BE7D1785EB9DB39",
            "maintainer": "ru_maniac",
            "location": "RU",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "built on: Tue Nov 29, 09:31:55 UTC+3\nplease note: running on c-toxcore!\nmore info on the matter: goo.gl/Gz5KhK & goo.gl/i2TZJr\n\ntox id for queries and general info: EBD2A7B649ABB10ED9F47E5113F04000F39D46F087CEB62FCCE1069471FD6915256D197F2A97",
            "last_ping": 1495114700
        },
        {
            "ipv4": "92.54.84.70",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [

            ],
            "public_key": "5625A62618CB4FCA70E147A71B29695F38CC65FF0CBD68AD46254585BE564802",
            "maintainer": "t3mp",
            "location": "RU",
            "status_udp": true,
            "status_tcp": false,
            "version": "2016010100",
            "motd": "tox-bootstrapd",
            "last_ping": 1495114700
        },
        {
            "ipv4": "195.93.190.6",
            "ipv6": "2a01:d0:ffff:a8a::2",
            "port": 33445,
            "tcp_ports": [
                33445
            ],
            "public_key": "FB4CE0DDEFEED45F26917053E5D24BDDA0FA0A3D83A672A9DA2375928B37023D",
            "maintainer": "strngr",
            "location": "UA",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "tox node at strngr.name",
            "last_ping": 1495114702
        },
        {
            "ipv4": "tox.uplinklabs.net",
            "ipv6": "tox.uplinklabs.net",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "1A56EA3EDF5DF4C0AEABBF3C2E4E603890F87E983CAC8A0D532A335F2C6E3E1F",
            "maintainer": "AbacusAvenger",
            "location": "US",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "tox-bootstrapd",
            "last_ping": 1495114700
        },
        {
            "ipv4": "toxnode.nek0.net",
            "ipv6": "toxnode.nek0.net",
            "port": 33445,
            "tcp_ports": [
                33445,
                3389
            ],
            "public_key": "20965721D32CE50C3E837DD75B33908B33037E6225110BFF209277AEAF3F9639",
            "maintainer": "Phsm",
            "location": "UA",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "tox-bootstrapd",
            "last_ping": 1495114700
        },
        {
            "ipv4": "95.215.44.78",
            "ipv6": "2a02:7aa0:1619::c6fe:d0cb",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "672DBE27B4ADB9D5FB105A6BB648B2F8FDB89B3323486A7A21968316E012023C",
            "maintainer": "HooinKyoma",
            "location": "SE",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Thanx to Hooin Kyoma",
            "last_ping": 1495114700
        },
        {
            "ipv4": "163.172.136.118",
            "ipv6": "2001:bc8:4400:2100::1c:50f",
            "port": 33445,
            "tcp_ports": [
                33445,
                3389
            ],
            "public_key": "2C289F9F37C20D09DA83565588BF496FAB3764853FA38141817A72E3F18ACA0B",
            "maintainer": "LittleVulpix",
            "location": "FR",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "LittleTox - your friendly neighbourhood tox node!",
            "last_ping": 1495114700
        },
        {
            "ipv4": "sorunome.de",
            "ipv6": "sorunome.de",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "02807CF4F8BB8FB390CC3794BDF1E8449E9A8392C5D3F2200019DA9F1E812E46",
            "maintainer": "Sorunome",
            "location": "DE",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Keep calm and pony on",
            "last_ping": 1495114700
        },
        {
            "ipv4": "37.97.185.116",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                33445
            ],
            "public_key": "E59A0E71ADA20D35BD1B0957059D7EF7E7792B3D680AE25C6F4DBBA09114D165",
            "maintainer": "Yani",
            "location": "NL",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Yani's node of pleasure and leisure",
            "last_ping": 1495114700
        },
        {
            "ipv4": "193.124.186.205",
            "ipv6": "2a02:f680:1:1100::542a",
            "port": 5228,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "9906D65F2A4751068A59D30505C5FC8AE1A95E0843AE9372EAFA3BAB6AC16C2C",
            "maintainer": "Cactus",
            "location": "RU",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "tox-bootstrapd",
            "last_ping": 1495114700
        },
        {
            "ipv4": "80.87.193.193",
            "ipv6": "2a01:230:2:6::46a8",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "B38255EE4B054924F6D79A5E6E5889EC94B6ADF6FE9906F97A3D01E3D083223A",
            "maintainer": "linxon",
            "location": "RU",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Tox DHT node by Linxon. Author ToxID: EC774ED05A7E71EEE2EBA939A27CD4FF403D7D79E1E685CFD0394B1770498217C6107E4D3C26",
            "last_ping": 1495114700
        },
        {
            "ipv4": "initramfs.io",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                33445,
                3389
            ],
            "public_key": "3F0A45A268367C1BEA652F258C85F4A66DA76BCAA667A49E770BCC4917AB6A25",
            "maintainer": "initramfs",
            "location": "TW",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "initramfs' Tox DHT Node",
            "last_ping": 1495114701
        },
        {
            "ipv4": "hibiki.eve.moe",
            "ipv6": "hibiki.eve.moe",
            "port": 33445,
            "tcp_ports": [
                33445
            ],
            "public_key": "D3EB45181B343C2C222A5BCF72B760638E15ED87904625AAD351C594EEFAE03E",
            "maintainer": "EveNeko",
            "location": "FR",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "tox-bootstrapd@hibiki.eve.moe",
            "last_ping": 1495114700
        },
        {
            "ipv4": "tox.deadteam.org",
            "ipv6": "tox.deadteam.org",
            "port": 33445,
            "tcp_ports": [
                33445
            ],
            "public_key": "C7D284129E83877D63591F14B3F658D77FF9BA9BA7293AEB2BDFBFE1A803AF47",
            "maintainer": "DeadTeam",
            "location": "DE",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Vive le TOX",
            "last_ping": 1495114702
        },
        {
            "ipv4": "46.229.52.198",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                33445
            ],
            "public_key": "813C8F4187833EF0655B10F7752141A352248462A567529A38B6BBF73E979307",
            "maintainer": "Stranger",
            "location": "UA",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Freedom to parrots!",
            "last_ping": 1495114702
        },
        {
            "ipv4": "node.tox.ngc.network",
            "ipv6": "node.tox.ngc.network",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "A856243058D1DE633379508ADCAFCF944E40E1672FF402750EF712E30C42012A",
            "maintainer": "Nolz",
            "location": "DE",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Unlike Others",
            "last_ping": 1495114700
        },
        {
            "ipv4": "144.217.86.39",
            "ipv6": "fe80::f816:3eff:fe61:92e3",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "7E5668E0EE09E19F320AD47902419331FFEE147BB3606769CFBE921A2A2FD34C",
            "maintainer": "velusip",
            "location": "CA",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Jera",
            "last_ping": 1495114700
        },
        {
            "ipv4": "185.14.30.213",
            "ipv6": "2a00:1ca8:a7::e8b",
            "port": 443,
            "tcp_ports": [
                3389,
                33445,
                443
            ],
            "public_key": "2555763C8C460495B14157D234DD56B86300A2395554BCAE4621AC345B8C1B1B",
            "maintainer": "dvor",
            "location": "NL",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Just another tox node.",
            "last_ping": 1495114700
        },
        {
            "ipv4": "85.21.144.224",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "8F738BBC8FA9394670BCAB146C67A507B9907C8E564E28C2B59BEBB2FF68711B",
            "maintainer": "himura",
            "location": "RU",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "My Tox ID, desu: EB8E9FFB08DC3C31F8450521A884B478A1B4452BBB4C86BDC7E2AD3CC681C146FF77CBEA21EA",
            "last_ping": 1495114700
        },
        {
            "ipv4": "tox.natalenko.name",
            "ipv6": "tox.natalenko.name",
            "port": 33445,
            "tcp_ports": [
                33445
            ],
            "public_key": "1CB6EBFD9D85448FA70D3CAE1220B76BF6FCE911B46ACDCF88054C190589650B",
            "maintainer": "post-factum",
            "location": "DE",
            "status_udp": true,
            "status_tcp": true,
            "version": "",
            "motd": "",
            "last_ping": 1495114702
        },
        {
            "ipv4": "37.187.122.30",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                33445,
                3389
            ],
            "public_key": "BEB71F97ED9C99C04B8489BB75579EB4DC6AB6F441B603D63533122F1858B51D",
            "maintainer": "dolohow",
            "location": "FR",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "#stay frosty 8218DB335926393789859EDF2D79AC4CC805ADF73472D08165FEA51555502A58AE84FCE7C3D4",
            "last_ping": 1495114700
        },
        {
            "ipv4": "completelyunoriginal.moe",
            "ipv6": "completelyunoriginal.moe",
            "port": 33445,
            "tcp_ports": [
                33445
            ],
            "public_key": "FBC7DED0B0B662D81094D91CC312D6CDF12A7B16C7FFB93817143116B510C13E",
            "maintainer": "SillyPeruvian",
            "location": "FR",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "Completely Unoriginal Tox Bootstrapper. For node maintenance or whatever: https://toxme.io/u/sillyperuvian",
            "last_ping": 1495114702
        },
        {
            "ipv4": "136.243.141.187",
            "ipv6": "2a01:4f8:212:2459::a:1337",
            "port": 443,
            "tcp_ports": [
                443,
                33445,
                3389
            ],
            "public_key": "6EE1FADE9F55CC7938234CC07C864081FC606D8FE7B751EDA217F268F1078A39",
            "maintainer": "CeBe",
            "location": "DE",
            "status_udp": true,
            "status_tcp": true,
            "version": "2016010100",
            "motd": "uTox is the future! - maintained by CeBe - contact: tox@cebe.cc - tox: 7F50119368DC8FD3B1ECAF5D18E3F8854F0484CEC5BBF625D420B8E38638733C02486E387AF8",
            "last_ping": 1495114700
        },
        {
            "ipv4": "tox.abilinski.com",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [
                33445
            ],
            "public_key": "0E9D7FEE2AA4B42A4C18FE81C038E32FFD8D907AAA7896F05AA76C8D31A20065",
            "maintainer": "flobe",
            "location": "CA",
            "status_udp": true,
            "status_tcp": true,
            "version": "",
            "motd": "",
            "last_ping": 1495114702
        },
        {
            "ipv4": "95.215.46.114",
            "ipv6": "2a02:7aa0:1619::bdbd:17b8",
            "port": 33445,
            "tcp_ports": [
                3389,
                33445
            ],
            "public_key": "5823FB947FF24CF83DDFAC3F3BAA18F96EA2018B16CC08429CB97FA502F40C23",
            "maintainer": "isotoxin",
            "location": "SE",
            "status_udp": true,
            "status_tcp": true,
            "version": "",
            "motd": "",
            "last_ping": 1495114700
        },
        {
            "ipv4": "46.101.197.175",
            "ipv6": "2a03:b0c0:3:d0::ac:5001",
            "port": 443,
            "tcp_ports": [
                3389,
                33445,
                443
            ],
            "public_key": "CD133B521159541FB1D326DE9850F5E56A6C724B5B8E5EB5CD8D950408E95707",
            "maintainer": "clearmartin",
            "location": "DE",
            "status_udp": false,
            "status_tcp": true,
            "version": "2014101200",
            "motd": "tox-bootstrapd",
            "last_ping": 1495114700
        },
        {
            "ipv4": "77.37.160.178",
            "ipv6": "-",
            "port": 33440,
            "tcp_ports": [

            ],
            "public_key": "CE678DEAFA29182EFD1B0C5B9BC6999E5A20B50A1A6EC18B91C8EBB591712416",
            "maintainer": "Madji",
            "location": "RU",
            "status_udp": false,
            "status_tcp": false,
            "version": "2016010100",
            "motd": "ru_maniac's secondary bootstrap node",
            "last_ping": 1495005620
        },
        {
            "ipv4": "77.37.142.179",
            "ipv6": "-",
            "port": 33445,
            "tcp_ports": [

            ],
            "public_key": "98F5830A426C6BF165F895F04B897AFC4F57331B4BE0561F583C9F323194227B",
            "maintainer": "ps",
            "location": "RU",
            "status_udp": false,
            "status_tcp": false,
            "version": "2016010100",
            "motd": "tox-bootstrapd",
            "last_ping": 1494344722
        },
        {
            "ipv4": "plfgr.eu.org",
            "ipv6": "plfgr.eu.org",
            "port": 33445,
            "tcp_ports": [

            ],
            "public_key": "F5A2E533EC720927FA970F508D949D5958F37889F039F50C905010244842656E",
            "maintainer": "nnnn20430",
            "location": "SI",
            "status_udp": false,
            "status_tcp": false,
            "version": "2016010100",
            "motd": "tox-bootstrapd",
            "last_ping": 1494390922
        },
        {
            "ipv4": "51.15.54.207",
            "ipv6": "2001:bc8:4700:2300::28:80d",
            "port": 33445,
            "tcp_ports": [

            ],
            "public_key": "1E64DBA45EC810C0BF3A96327DC8A9D441AB262C14E57FCE11ECBCE355305239",
            "maintainer": "biodamage",
            "location": "NL",
            "status_udp": false,
            "status_tcp": false,
            "version": "2016010100",
            "motd": "Hello my tox ID DCFE79BA65B1017138BB22F074FDCD00A49663B76044E53321CF482CC17CD60617623C3B75A4",
            "last_ping": 1494951560
        }
    ]
}
`)

func toxnodesJsonBytes() ([]byte, error) {
	return _toxnodesJson, nil
}

func toxnodesJson() (*asset, error) {
	bytes, err := toxnodesJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "toxnodes.json", size: 26339, mode: os.FileMode(420), modTime: time.Unix(1495114530, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"toxnodes.json": toxnodesJson,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"toxnodes.json": &bintree{toxnodesJson, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

